// This file is auto-generated by @hey-api/openapi-ts

export { graphUrlsAdd, type Options } from './sdk.gen';
export type { ClientOptions, Example, GraphUrlsAddData, GraphUrlsAddResponse, GraphUrlsAddResponses } from './types.gen';
