// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ArtistId = number;

/**
 * Artist
 */
export type Artist = {
    id: ArtistId;
    /**
     * Name
     */
    name: string;
    /**
     * Wikipedia Title
     */
    wikipedia_title?: string | null;
    /**
     * Wikipedia Description
     */
    wikipedia_description?: string | null;
    /**
     * Wikipedia Summary
     */
    wikipedia_summary?: string | null;
};

/**
 * Edge
 */
export type Edge = {
    source: Artist;
    target: Artist;
    /**
     * Wikipedia Description
     */
    wikipedia_description?: string | null;
};

export type GraphUrlsEdgesData = {
    body?: never;
    path?: never;
    query: {
        artist: number;
    };
    url: '/api/edges';
};

export type GraphUrlsEdgesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Edge>;
};

export type GraphUrlsEdgesResponse = GraphUrlsEdgesResponses[keyof GraphUrlsEdgesResponses];

export type GraphUrlsSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
    };
    url: '/api/search';
};

export type GraphUrlsSearchResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Artist>;
};

export type GraphUrlsSearchResponse = GraphUrlsSearchResponses[keyof GraphUrlsSearchResponses];

export type GraphUrlsEdgeDescriptionData = {
    body?: never;
    path?: never;
    query: {
        source: number;
        target: number;
    };
    url: '/api/edge-description';
};

export type GraphUrlsEdgeDescriptionResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Edge>;
};

export type GraphUrlsEdgeDescriptionResponse = GraphUrlsEdgeDescriptionResponses[keyof GraphUrlsEdgeDescriptionResponses];
