// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type Example = number;

export type GraphUrlsAddData = {
    body?: never;
    path?: never;
    query: {
        /**
         * A
         */
        a: number;
        /**
         * B
         */
        b: number;
    };
    url: '/api/add';
};

export type GraphUrlsAddResponses = {
    /**
     * OK
     */
    200: Example;
};

export type GraphUrlsAddResponse = GraphUrlsAddResponses[keyof GraphUrlsAddResponses];
