# Generated by Django 6.0 on 2026-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('is_adderall_sold', models.BooleanField()),
                ('appears_licensed_pharmacy', models.BooleanField()),
                ('explanation', models.TextField()),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
