# Generated by Django 6.0 on 2026-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_policyviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyviolation',
            name='uses_visa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
