# Generated by Django 6.0 on 2026-02-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_policyviolation_uses_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyviolation',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
